// Frozen wire contract. Importing these instead of string literals is what
// stops a client listener and a server emitter from silently drifting apart.
export const EVENTS = Object.freeze({
  // client -> server
  JOIN_CHAMBER: 'JOIN_CHAMBER',
  LEAVE_CHAMBER: 'LEAVE_CHAMBER',
  REQUEST_QUEUE_SNAPSHOT: 'REQUEST_QUEUE_SNAPSHOT',
  // server -> client
  QUEUE_SNAPSHOT: 'QUEUE_SNAPSHOT',
  TOKEN_CREATED: 'TOKEN_CREATED',
  TOKEN_STATUS_CHANGED: 'TOKEN_STATUS_CHANGED',
  CALL_NEXT_TOKEN: 'CALL_NEXT_TOKEN',
  EXECUTE_AUDIO_ANNOUNCEMENT: 'EXECUTE_AUDIO_ANNOUNCEMENT',
  DOCTOR_BREAK_TOGGLE: 'DOCTOR_BREAK_TOGGLE',
  DOCTOR_SESSION_CHANGED: 'DOCTOR_SESSION_CHANGED',
  HOSPITAL_STATE_CHANGED: 'HOSPITAL_STATE_CHANGED',
  HOSPITAL_DEBOARDED: 'HOSPITAL_DEBOARDED',
  SUBMISSION_STATUS_CHANGED: 'SUBMISSION_STATUS_CHANGED',
  TRANSACTION_RECORDED: 'TRANSACTION_RECORDED',
});
